In [1]:
import subprocess
import os
import base64
import pandas as pd

In [2]:
dataset = pd.read_csv('training_set/cleaned_agreed.csv')

In [3]:
# os.chdir('/home/aselhidayat/Documents/Academics_6/NLP/indo_tagger/tagger')

In [4]:
# tagset = {}

# for index, row in dataset.iterrows():
#     kalimat = row['kalimat']
#     kata = row['kata']
#     tag_sets = subprocess.check_output(f'./tag.sh -raw "{kalimat}"', shell=True).decode('utf-8').split('\n')
    
#     for ts in tag_sets:
#         if kata in ts:
#             _, tag = ts.split('\t')
#             print(kata, tag)
#             tagset[index] = tag
#             break

In [5]:
# dataset.head()

In [6]:
# dataset['pos'] = dataset.index.map(tagset)

In [7]:
# cleaned_dataset = dataset.drop(7272)

In [8]:
# os.chdir('/home/aselhidayat/Documents/Academics_6/NLP/ta_nlp')

In [9]:
# !ls training_set

In [10]:
# cleaned_dataset.to_csv('training_set/pos_tagged.csv', index=False)

In [14]:
pos = {'0101': 'VB',
 '0102': 'NN',
 '0103': 'VB',
 '0201': 'NN',
 '0202': 'NN',
 '0203': 'NN',
 '0204': 'NN',
 '0301': 'NN',
 '0302': 'NN',
 '0303': 'NN',
 '0304': 'NN',
 '0401': 'NN',
 '0402': 'NN',
 '0403': 'NN',
 '0501': 'NN',
 '0502': 'NN',
 '0503': 'NN',
 '0601': 'NN',
 '0602': 'NN',
 '0603': 'NN',
 '0701': 'NN',
 '0702': 'NN',
 '0703': 'NN',
 '0801': 'NN',
 '0802': 'NN',
 '0803': 'NN',
 '0804': 'NN',
 '0901': 'NN',
 '0902': 'NN',
 '0903': 'NN',
 '0904': 'NN',
 '1001': 'NN',
 '1002': 'NN',
 '1003': 'NN',
 '1004': 'NN',
 '1005': 'NN',
 '1006': 'NN',
 '1101': 'NN',
 '1102': 'NN',
 '1103': 'NN',
 '1104': 'NN',
 '1201': 'NN',
 '1202': 'NN',
 '1301': 'NN',
 '1302': 'NN',
 '1303': 'NN',
 '1304': 'NN',
 '1401': 'NN',
 '1402': 'NN',
 '1403': 'NN',
 '1501': 'NN',
 '1502': 'NN',
 '1503': 'NN',
 '1504': 'NN',
 '1601': 'NN',
 '1602': 'NN',
 '1701': 'NN',
 '1702': 'NN',
 '1703': 'NN',
 '1801': 'NN',
 '1802': 'NN',
 '1803': 'NN',
 '1804': 'JJ',
 '1901': 'NN',
 '1902': 'NN',
 '1903': 'NN',
 '1904': 'NN',
 '1905': 'NN',
 '1906': 'NN',
 '1907': 'VB',
 '2001': 'VB',
 '2002': 'VB',
 '2101': 'VB',
 '2102': 'VB',
 '2103': 'VB',
 '2104': 'VB',
 '2105': 'VB',
 '2106': 'VB',
 '2201': 'VB',
 '2202': 'VB',
 '2203': 'VB',
 '2204': 'VB',
 '2301': 'VB',
 '2302': 'VB',
 '2401': 'VB',
 '2402': 'VB',
 '2403': 'VB',
 '2501': 'VB',
 '2502': 'VB',
 '2503': 'VB',
 '2504': 'VB',
 '2601': 'VB',
 '2602': 'VB',
 '2701': 'VB',
 '2702': 'VB',
 '2703': 'VB',
 '2704': 'VB',
 '2801': 'VB',
 '2802': 'VB',
 '2901': 'VB',
 '2902': 'VB',
 '2903': 'VB',
 '2904': 'VB',
 '2905': 'VB',
 '2906': 'VB',
 '3001': 'VB',
 '3002': 'VB',
 '3003': 'VB',
 '3004': 'VB',
 '3005': 'VB',
 '3006': 'VB',
 '3007': 'VB',
 '3101': 'VB',
 '3102': 'VB',
 '3103': 'VB',
 '3104': 'VB',
 '3105': 'VB',
 '3106': 'VB',
 '3201': 'VB',
 '3202': 'VB',
 '3203': 'VB',
 '3204': 'VB',
 '3301': 'VB',
 '3302': 'VB',
 '3303': 'VB',
 '3304': 'VB',
 '3305': 'VB',
 '3401': 'NN',
 '3402': 'NN',
 '3403': 'NN',
 '3501': 'NN',
 '3502': 'NN',
 '3503': 'NN',
 '3601': 'NN',
 '3602': 'NN',
 '3603': 'NN',
 '3701': 'NN',
 '3702': 'NN',
 '3703': 'NN',
 '3704': 'NN',
 '3705': 'NN',
 '3801': 'JJ',
 '3802': 'JJ',
 '3803': 'VB',
 '3901': 'JJ',
 '3902': 'RB',
 '3903': 'RB',
 '4001': 'NN',
 '4002': 'JJ',
 '4003': 'JJ',
 '4004': 'JJ',
 '4005': 'JJ',
 '4006': 'JJ',
 '4007': 'IN',
 '4008': 'IN',
 '4009': 'IN',
 '4010': 'IN',
 '4011': 'IN',
 '4012': 'IN',
 '4101': 'JJ',
 '4102': 'JJ',
 '4103': 'JJ',
 '4104': 'JJ',
 '4201': 'NN',
 '4202': 'NN',
 '4203': 'NN',
 '4204': 'NN',
 '4205': 'VB',
 '4206': 'JJ',
 '4207': 'NN',
 '4301': 'NN',
 '4302': 'NN',
 '4303': 'NN',
 '4304': 'RB',
 '4401': 'NN',
 '4402': 'NN',
 '4403': 'NN',
 '4404': 'NN',
 '4405': 'JJ',
 '4406': 'IN',
 '4407': 'IN',
 '4408': 'IN',
 '4501': 'NN',
 '4502': 'NN',
 '4503': 'JJ',
 '4504': 'JJ',
 '4601': 'NN',
 '4602': 'JJ',
 '4603': 'JJ',
 '4701': 'NN',
 '4702': 'NN',
 '4703': 'JJ',
 '4801': 'JJ',
 '4802': 'JJ',
 '4803': 'JJ',
 '4901': 'NN',
 '4902': 'NN',
 '4903': 'NN',
 '4904': 'JJ',
 '4905': 'JJ',
 '4906': 'JJ',
 '5001': 'NN',
 '5002': 'NN',
 '5003': 'NN',
 '5101': 'JJ',
 '5102': 'JJ',
 '5103': 'JJ',
 '5104': 'JJ',
 '5105': 'JJ',
 '5106': 'JJ',
 '5107': 'JJ',
 '5201': 'NN',
 '5202': 'JJ',
 '5203': 'JJ',
 '5204': 'JJ',
 '5205': 'JJ',
 '5206': 'JJ',
 '5301': 'JJ',
 '5302': 'JJ',
 '5303': 'JJ',
 '5401': 'NN',
 '5402': 'JJ',
 '5403': 'JJ',
 '5404': 'JJ',
 '5405': 'JJ',
 '5406': 'JJ',
 '5501': 'JJ',
 '5502': 'JJ'}

In [20]:
def pos_tagging(s):
    if s.isnumeric():
        try:
            return pos[s]
        except KeyError:
            return None
    
    if s[-1] != 'x':
        return 'NNP'
    else:
        return 'MWE'

dataset['pos'] = dataset['sense'].apply(pos_tagging)

In [28]:
pd.set_option('display.max_colwidth', -1)
dataset[dataset['pos'].isna()]

,kalimat_id,kata,sense,kalimat,pos
4007,1010924,mengikat,2303,tetapi karna terikat dengan budi baik ayah angkatnya dan duryudana yang mengangkatnya menjadi raja dan utang budi itu jauh lebih mengikat daripada hubungan darah yang kurang terpelihara,None
4014,1010906,mengikat,2303,selain itu keputusan sebagai sebuah regulasi dapat diterapkan secara langsung tetapi perjanjian ec pasal 249 menyatakan bahwa keputusan keputusan ini dapat mengikat hanya bagi mereka yang ditujukan apakah itu negara anggota perusahaan atau perorangan,None
4024,1010935,mengikat,2303,pbb saat ini terdiri dari lima organ utama yaitu majelis umum dewan musyawarah utama dewan keamanan dewan yang membuat beberapa resolusi mengikat mengenai perdamaian dan keamanan dewan ekonomi dan sosial ecosoc dewan yang mendorong kerjasama dan pembangunan ekonomi sosial internasional sekretariat yang berfungsi menyediakan studi informasi dan fasilitas yang dibutuhkan pbb dan mahkamah internasional badan yudisial utama,None
7404,1098270,tinggi,5013,menampilkan dua akrobat yang melayang tinggi di atas kerumunan digantung pada balon apung putih selama memainkan blackout sebuah lagu dari album absolution,None
7410,1078609,tinggi,5016,distilasi kering biasanya membutuhkan suhu yang lebih tinggi dibanding distilasi biasa,None

In [32]:
dataset.iloc[4007]['sense']

'2303'